[versions]
activityVersion = "1.8.0"
agp = "8.5.1"
androidGifDrawable = "1.2.23"
appcompatVersion = "1.6.1"
circleimageviewVersion = "3.0.0"
firebaseUiStorage = "8.0.0"
glide = "4.16.0"
googleMaterial = "1.5.0"
imagepicker = "2.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
lifecycleRuntimeKtx = "2.8.6"
activityCompose = "1.9.2"
composeBom = "2024.04.01"
horizontalcalendar= "1.2.2"
circleimageview = "3.1.0"

materialVersion = "3"
firebaseAuth = "23.0.0"
firebaseFirestore = "25.1.0"
googleGmsGoogleServices = "4.4.2"

[libraries]
activity-v180 = { module = "androidx.activity:activity", version.ref = "activityVersion" }
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
circleimageview-v300 = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageviewVersion" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
firebase-ui-storage = { module = "com.firebaseui:firebase-ui-storage", version.ref = "firebaseUiStorage" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepicker" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
material-v150 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
horizontalcalendar = {group = "io.github.b-sahana", name = "horizontalcalendar", version.ref = "horizontalcalendar"}
circleimageview = {group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview"}
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
x-3-10 = { module = "com.google.gms.google-services:4.3.10" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

